### ISSUE TITLE
OOM

### ISSUE THREAD

**Issue by plastic-kai** [Chenrenzhan/IDoodles#1]
FATAL EXCEPTION: main
                                                                    Process: com.example.idoodles, PID: 5346
                                                                    java.lang.OutOfMemoryError: Failed to allocate a 12769932 byte allocation with 2175232 free bytes and 2MB until OOM
                                                                        at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                                        at android.graphics.Bitmap.nativeCreate(Native Method)
                                                                        at android.graphics.Bitmap.createBitmap(Bitmap.java:831)
                                                                        at android.graphics.Bitmap.createBitmap(Bitmap.java:808)
                                                                        at android.graphics.Bitmap.createBitmap(Bitmap.java:775)
                                                                        at com.example.idoodles.util.UndoAndRedo.initial(UndoAndRedo.java:43)
                                                                        at com.example.idoodles.util.UndoAndRedo.<init>(UndoAndRedo.java:29)
                                                                        at com.example.idoodles.util.UndoAndRedo.<init>(UndoAndRedo.java:0)
                                                                        at com.example.idoodles.util.UndoAndRedo$Instace.<clinit>(UndoAndRedo.java:33)
                                                                        at com.example.idoodles.util.UndoAndRedo.getInstance(UndoAndRedo.java:37)
                                                                        at com.example.idoodles.view.DrawView.initial(DrawView.java:52)
                                                                        at com.example.idoodles.view.DrawView.<init>(DrawView.java:46)
                                                                        at com.example.idoodles.view.CrayonDrawView.<init>(CrayonDrawView.java:0)
                                                                        at com.example.idoodles.util.PaintFactory.createPaint(PaintFactory.java:89)
                                                                        at com.example.idoodles.MainActivity.initCanvasView(MainActivity.java:100)
                                                                        at com.example.idoodles.MainActivity.access$200(MainActivity.java:26)
                                                                        at com.example.idoodles.MainActivity$1.onPreDraw(MainActivity.java:122)
                                                                        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
                                                                        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2063)
                                                                        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1115)
                                                                        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6023)
                                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                        at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                        at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5422)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by plastic-kai** [comment]
solved: 

<application
android:name=".ParaseApplication"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:theme="@style/AppTheme"
        android:largeHeap="true"
        >
